FileVersion = 1
Dependencies = {corlib = "*", SDL2 = "*"}

[Project]
Name = "Slime-Slammer"
TargetType = "BeefGUIApplication"
StartupObject = "bounty_game.Program"
DefaultNamespace = "bounty_game"
Aliases = ["Slime slammer"]

[Platform.Windows]
IconFile = "D:\\Desktop\\bounty-game\\icon.ico"

[Configs.Debug.Win64]
PostBuildCmds = ["CopyFilesIfNewer(\"$(ProjectDir)/Assets\",\"$(WorkspaceDir)/Slime-Slammer\")\nCopyFilesIfNewer(\"$(BuildDir)\",\"$(ProjectDir)\")"]

[[Configs.Debug.Win64.DistinctOptions]]
Filter = ""

[Configs.Release.Win64]
PostBuildCmds = ["CopyFilesIfNewer(\"$(ProjectDir)/Assets\",\"$(WorkspaceDir)/bounty-game\")\nCopyFilesIfNewer(\"$(BuildDir)\",\"$(ProjectDir)\")"]

[Configs.Paranoid.Win64]
PostBuildCmds = ["CopyFilesIfNewer(\"$(ProjectDir)/Assets\",\"$(WorkspaceDir)/SDL2_Tut\")\nCopyFilesIfNewer(\"$(BuildDir)\",\"$(ProjectDir)\")"]

[Configs.Test.Win64]
PostBuildCmds = ["CopyFilesIfNewer(\"$(ProjectDir)/Assets\",\"$(WorkspaceDir)/SDL2_Tut\")\nCopyFilesIfNewer(\"$(BuildDir)\",\"$(ProjectDir)\")"]
